#!/bin/bash

chrono_convert='if (!require(ape)) install.require("ape")
allfile <- list.files(pattern = "treefile")
for (i in allfile){
	name <- strsplit(i, ".", fixed = TRUE)[[1]][1]
	name <- paste(name, ".chrono", sep = "")

	t <- read.tree(i)
	chronogram <- chronos(t, lambda = 1, model = "correlated")
	write.tree(chronogram, file = name)
}'


read -p "Run on current folder?(Y/n) " answer
if [[ "${answer}" == "y" ]] || [[ "${answer}" == "Y" ]]; then

  dir=$(pwd)
  rm -rf ${dir}/chrono_brlen ${dir}/chronogram
  mkdir ${dir}/chrono_brlen ${dir}/chronogram

  # Convert the phylogram to chronogram using chronos() in ape R package
  Rscript <(echo "${chrono_convert}") 2>&1 >/dev/null
  mv ${dir}/*chrono ${dir}/chronogram
  
  # Branch length extraction
  for f in ${dir}/chronogram/*chrono; do
    name=$(basename ${f} | cut -d "." -f 1)
    gene=$(echo "${name}" | cut -d "-" -f 1)
    taxon=$(echo "${name}" | cut -d "-" -f 2)

    ig_mrca=$(nw_distance -n -m p ${f} | grep "${taxon}_Z" | cut -d $'\t' -f 2)

    echo -e "${gene}\t${calculation}\t${ig_mrca}" >>${dir}/chrono_brlen/${taxon}.brlen
  done

fi
